"""initial schema

Revision ID: 9355077ef709
Revises: 
Create Date: 2026-09-18 16:09:13.584463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9355077ef709'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_nonces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.Column('nonce', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nonce')
    )
    op.create_index(op.f('ix_auth_nonces_id'), 'auth_nonces', ['id'], unique=False)
    op.create_index(op.f('ix_auth_nonces_wallet_address'), 'auth_nonces', ['wallet_address'], unique=False)
    op.create_table('indexer_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('last_processed_block', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_address')
    )
    op.create_index(op.f('ix_indexer_checkpoints_id'), 'indexer_checkpoints', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=True)
    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invites_code_hash'), 'invites', ['code_hash'], unique=True)
    op.create_index(op.f('ix_invites_id'), 'invites', ['id'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('AUTH_FAILURE', 'AUTH_SUCCESS', 'INVITE_CREATED', 'INVITE_REDEEMED', 'INVITE_REDEMPTION_DENIED', 'INVITE_REVOKED', 'MEMBERSHIP_SUSPENDED', 'MEMBERSHIP_REACTIVATED', 'ROLE_CHANGED', 'SETTLEMENT_DETAIL_VIEWED', 'SETTLEMENT_DETAIL_CREATED', 'SETTLEMENT_DETAIL_REVOKED', 'DISPUTE_EVIDENCE_VIEWED', 'DISPUTE_EVIDENCE_SUBMITTED', 'DISPUTE_ASSIGNMENT_CREATED', 'DISPUTE_ASSIGNMENT_REVOKED', 'REPORT_FILED', 'REPORT_REVIEWED', 'RATE_LIMIT_TRIGGERED', 'ADMIN_BOOTSTRAPPED', name='securityeventtype', create_constraint=True), nullable=False),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_id'), 'security_events', ['id'], unique=False)
    op.create_table('settlement_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('encrypted_payload', sa.LargeBinary(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlement_details_id'), 'settlement_details', ['id'], unique=False)
    op.create_index(op.f('ix_settlement_details_owner_user_id'), 'settlement_details', ['owner_user_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=True),
    sa.Column('invite_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('MEMBER', 'MODERATOR', 'ADMIN', name='memberrole', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', name='membershipstatus', create_constraint=True), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('suspended_at', sa.DateTime(), nullable=True),
    sa.Column('suspended_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['invite_id'], ['invites.id'], ),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_membership_user')
    )
    op.create_index(op.f('ix_memberships_id'), 'memberships', ['id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('p2p_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('onchain_order_id', sa.Integer(), nullable=False),
    sa.Column('escrow_tx_hash', sa.String(), nullable=True),
    sa.Column('token_address', sa.String(), nullable=False),
    sa.Column('seller_wallet', sa.String(), nullable=False),
    sa.Column('buyer_wallet', sa.String(), nullable=True),
    sa.Column('arbiter_snapshot_wallet', sa.String(), nullable=True),
    sa.Column('crypto_amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('onchain_status', sa.Enum('OPEN', 'CLAIMED', 'PAID', 'DISPUTED', 'RELEASED', 'REFUNDED', 'CANCELLED', name='orderstatus', create_constraint=True), nullable=False),
    sa.Column('was_disputed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_block', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('fiat_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fiat_currency', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('quoted_rate', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('settlement_detail_id', sa.Integer(), nullable=True),
    sa.Column('settlement_snapshot_payload', sa.LargeBinary(), nullable=True),
    sa.Column('settlement_snapshot_payment_method', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['settlement_detail_id'], ['settlement_details.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('onchain_order_id', name='uq_order_onchain_id')
    )
    op.create_index(op.f('ix_p2p_orders_arbiter_snapshot_wallet'), 'p2p_orders', ['arbiter_snapshot_wallet'], unique=False)
    op.create_index(op.f('ix_p2p_orders_buyer_wallet'), 'p2p_orders', ['buyer_wallet'], unique=False)
    op.create_index(op.f('ix_p2p_orders_escrow_tx_hash'), 'p2p_orders', ['escrow_tx_hash'], unique=False)
    op.create_index(op.f('ix_p2p_orders_id'), 'p2p_orders', ['id'], unique=False)
    op.create_index(op.f('ix_p2p_orders_onchain_order_id'), 'p2p_orders', ['onchain_order_id'], unique=False)
    op.create_index(op.f('ix_p2p_orders_seller_wallet'), 'p2p_orders', ['seller_wallet'], unique=False)
    op.create_table('arbiter_resolutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('resolved_by_wallet', sa.String(), nullable=False),
    sa.Column('recipient_wallet', sa.String(), nullable=False),
    sa.Column('reasoning', sa.String(), nullable=False),
    sa.Column('resolve_tx_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['p2p_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arbiter_resolutions_id'), 'arbiter_resolutions', ['id'], unique=False)
    op.create_index(op.f('ix_arbiter_resolutions_order_id'), 'arbiter_resolutions', ['order_id'], unique=False)
    op.create_table('dispute_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('assigned_user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['p2p_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispute_assignments_assigned_user_id'), 'dispute_assignments', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_dispute_assignments_id'), 'dispute_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_dispute_assignments_order_id'), 'dispute_assignments', ['order_id'], unique=False)
    op.create_table('dispute_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.String(), nullable=False),
    sa.Column('storage_ref', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['p2p_orders.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispute_evidence_id'), 'dispute_evidence', ['id'], unique=False)
    op.create_index(op.f('ix_dispute_evidence_order_id'), 'dispute_evidence', ['order_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_user_id', sa.Integer(), nullable=False),
    sa.Column('reported_user_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['p2p_orders.id'], ),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_dispute_evidence_order_id'), table_name='dispute_evidence')
    op.drop_index(op.f('ix_dispute_evidence_id'), table_name='dispute_evidence')
    op.drop_table('dispute_evidence')
    op.drop_index(op.f('ix_dispute_assignments_order_id'), table_name='dispute_assignments')
    op.drop_index(op.f('ix_dispute_assignments_id'), table_name='dispute_assignments')
    op.drop_index(op.f('ix_dispute_assignments_assigned_user_id'), table_name='dispute_assignments')
    op.drop_table('dispute_assignments')
    op.drop_index(op.f('ix_arbiter_resolutions_order_id'), table_name='arbiter_resolutions')
    op.drop_index(op.f('ix_arbiter_resolutions_id'), table_name='arbiter_resolutions')
    op.drop_table('arbiter_resolutions')
    op.drop_index(op.f('ix_p2p_orders_seller_wallet'), table_name='p2p_orders')
    op.drop_index(op.f('ix_p2p_orders_onchain_order_id'), table_name='p2p_orders')
    op.drop_index(op.f('ix_p2p_orders_id'), table_name='p2p_orders')
    op.drop_index(op.f('ix_p2p_orders_escrow_tx_hash'), table_name='p2p_orders')
    op.drop_index(op.f('ix_p2p_orders_buyer_wallet'), table_name='p2p_orders')
    op.drop_index(op.f('ix_p2p_orders_arbiter_snapshot_wallet'), table_name='p2p_orders')
    op.drop_table('p2p_orders')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_settlement_details_owner_user_id'), table_name='settlement_details')
    op.drop_index(op.f('ix_settlement_details_id'), table_name='settlement_details')
    op.drop_table('settlement_details')
    op.drop_index(op.f('ix_security_events_id'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_invites_id'), table_name='invites')
    op.drop_index(op.f('ix_invites_code_hash'), table_name='invites')
    op.drop_table('invites')
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_indexer_checkpoints_id'), table_name='indexer_checkpoints')
    op.drop_table('indexer_checkpoints')
    op.drop_index(op.f('ix_auth_nonces_wallet_address'), table_name='auth_nonces')
    op.drop_index(op.f('ix_auth_nonces_id'), table_name='auth_nonces')
    op.drop_table('auth_nonces')
    # ### end Alembic commands ###

    # Phase 2B.4 — bug real de compatibilidad con PostgreSQL, encontrado
    # corriendo downgrade/upgrade contra un Postgres real: autogenerate NUNCA
    # emite esto, pero en PostgreSQL cada `sa.Enum(...)` de SQLAlchemy crea un
    # TYPE nativo SEPARADO de las tablas que lo usan (ver ENFORCEMENT_LEVELS.md
    # y el informe de Phase 2B.4 — confirmado con
    # information_schema/pg_type, no solo inferido). Dropear solo las tablas
    # deja esos 4 tipos huerfanos, y una re-ejecucion de upgrade() falla con
    # "type ... already exists" al intentar CREATE TYPE de nuevo. Invisible en
    # SQLite: ahi el enum es solo un CHECK inline en la columna (Phase 2B.1),
    # no un objeto de esquema propio — por eso este bug no aparecio hasta
    # correr contra Postgres real. No-op en SQLite (dialect.name distinto).
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        for enum_name in ("securityeventtype", "orderstatus", "membershipstatus", "memberrole"):
            op.execute(f"DROP TYPE IF EXISTS {enum_name}")
