"""whatsapp sandbox tables

Revision ID: 989d2c51d5ca
Revises: 402dd0331175
Create Date: 2026-09-19 09:30:00.633342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '989d2c51d5ca'
down_revision: Union[str, Sequence[str], None] = '402dd0331175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('whatsapp_id', sa.String(), nullable=False),
    sa.Column('state', sa.Enum('IDLE', 'AWAITING_LINK', 'AWAITING_INVITE_CODE', 'MENU', 'BUY_SELECT_OFFER', 'SELL_AWAITING_AMOUNT', 'SELL_AWAITING_RATE', 'SELL_AWAITING_CONFIRM', 'DISPUTE_SELECT_TRADE', name='conversationstate', create_constraint=True), nullable=False),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_sessions_id'), 'conversation_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_sessions_whatsapp_id'), 'conversation_sessions', ['whatsapp_id'], unique=True)
    op.create_table('processed_webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'message_id', name='uq_webhook_event_provider_message')
    )
    op.create_index(op.f('ix_processed_webhook_events_id'), 'processed_webhook_events', ['id'], unique=False)
    op.create_table('whatsapp_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('whatsapp_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('link_token_hash', sa.String(), nullable=True),
    sa.Column('link_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_links_id'), 'whatsapp_links', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_links_link_token_hash'), 'whatsapp_links', ['link_token_hash'], unique=False)
    op.create_index(op.f('ix_whatsapp_links_user_id'), 'whatsapp_links', ['user_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_links_whatsapp_id'), 'whatsapp_links', ['whatsapp_id'], unique=True)
    # ### end Alembic commands ###

    # NOT autogenerated: models.py added SecurityEventType.WHATSAPP_ACCOUNT_LINKED
    # this phase, but the EXISTING security_events.action enum/CHECK was
    # frozen with its original member list back in 9355077ef709 -- adding a
    # Python enum member never retroactively updates an already-created
    # native Postgres TYPE or SQLite CHECK constraint (found empirically: a
    # real Alembic-migrated Postgres run rejected
    # SecurityEventType.WHATSAPP_ACCOUNT_LINKED with "invalid input value for
    # enum securityeventtype" -- invisible when a test uses create_all(),
    # which always regenerates the CHECK from the CURRENT model).
    _OLD_ACTIONS = (
        'AUTH_FAILURE', 'AUTH_SUCCESS', 'INVITE_CREATED', 'INVITE_REDEEMED', 'INVITE_REDEMPTION_DENIED',
        'INVITE_REVOKED', 'MEMBERSHIP_SUSPENDED', 'MEMBERSHIP_REACTIVATED', 'ROLE_CHANGED',
        'SETTLEMENT_DETAIL_VIEWED', 'SETTLEMENT_DETAIL_CREATED', 'SETTLEMENT_DETAIL_REVOKED',
        'DISPUTE_EVIDENCE_VIEWED', 'DISPUTE_EVIDENCE_SUBMITTED', 'DISPUTE_ASSIGNMENT_CREATED',
        'DISPUTE_ASSIGNMENT_REVOKED', 'REPORT_FILED', 'REPORT_REVIEWED', 'RATE_LIMIT_TRIGGERED',
        'ADMIN_BOOTSTRAPPED',
    )
    _NEW_ACTIONS = _OLD_ACTIONS + ('WHATSAPP_ACCOUNT_LINKED',)

    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        # ADD VALUE is transaction-safe on PG 12+ as long as the new value is
        # never USED within this same transaction (it isn't -- this only adds it).
        op.execute("ALTER TYPE securityeventtype ADD VALUE IF NOT EXISTS 'WHATSAPP_ACCOUNT_LINKED'")
    else:
        with op.batch_alter_table('security_events') as batch_op:
            batch_op.alter_column(
                'action',
                existing_type=sa.Enum(*_OLD_ACTIONS, name='securityeventtype', create_constraint=True),
                type_=sa.Enum(*_NEW_ACTIONS, name='securityeventtype', create_constraint=True),
            )


def downgrade() -> None:
    """Downgrade schema."""
    _OLD_ACTIONS = (
        'AUTH_FAILURE', 'AUTH_SUCCESS', 'INVITE_CREATED', 'INVITE_REDEEMED', 'INVITE_REDEMPTION_DENIED',
        'INVITE_REVOKED', 'MEMBERSHIP_SUSPENDED', 'MEMBERSHIP_REACTIVATED', 'ROLE_CHANGED',
        'SETTLEMENT_DETAIL_VIEWED', 'SETTLEMENT_DETAIL_CREATED', 'SETTLEMENT_DETAIL_REVOKED',
        'DISPUTE_EVIDENCE_VIEWED', 'DISPUTE_EVIDENCE_SUBMITTED', 'DISPUTE_ASSIGNMENT_CREATED',
        'DISPUTE_ASSIGNMENT_REVOKED', 'REPORT_FILED', 'REPORT_REVIEWED', 'RATE_LIMIT_TRIGGERED',
        'ADMIN_BOOTSTRAPPED',
    )
    _NEW_ACTIONS = _OLD_ACTIONS + ('WHATSAPP_ACCOUNT_LINKED',)

    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        # SQLite CHECK constraints are freely recreatable via batch mode --
        # a genuine, full revert (no data-loss caveat, unlike Postgres below).
        with op.batch_alter_table('security_events') as batch_op:
            batch_op.alter_column(
                'action',
                existing_type=sa.Enum(*_NEW_ACTIONS, name='securityeventtype', create_constraint=True),
                type_=sa.Enum(*_OLD_ACTIONS, name='securityeventtype', create_constraint=True),
            )
    # else: PostgreSQL has no ALTER TYPE ... DROP VALUE -- removing an enum
    # value requires recreating the entire type (rename, create new, migrate
    # every dependent column, drop old), which is only safe with a real
    # row-by-row data audit. Deliberately NOT implemented here (no real user
    # data exists in this sandbox phase to justify the risk) -- a downgrade
    # on PostgreSQL leaves WHATSAPP_ACCOUNT_LINKED in the native type, which
    # is a documented, known limitation, not a silent bug: nothing above this
    # migration will ever produce a row using that value once downgraded
    # (the WhatsApp tables themselves are gone), so the extra enum value is
    # inert, not incorrect.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_links_whatsapp_id'), table_name='whatsapp_links')
    op.drop_index(op.f('ix_whatsapp_links_user_id'), table_name='whatsapp_links')
    op.drop_index(op.f('ix_whatsapp_links_link_token_hash'), table_name='whatsapp_links')
    op.drop_index(op.f('ix_whatsapp_links_id'), table_name='whatsapp_links')
    op.drop_table('whatsapp_links')
    op.drop_index(op.f('ix_processed_webhook_events_id'), table_name='processed_webhook_events')
    op.drop_table('processed_webhook_events')
    op.drop_index(op.f('ix_conversation_sessions_whatsapp_id'), table_name='conversation_sessions')
    op.drop_index(op.f('ix_conversation_sessions_id'), table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    # ### end Alembic commands ###

    # Same PostgreSQL-only gotcha fixed in 402dd0331175 / 9355077ef709: a
    # SQLAlchemy Enum(create_constraint=True) creates a genuine native
    # Postgres TYPE separate from the table, which DROP TABLE never removes —
    # without this, a downgrade->upgrade cycle fails with "type already
    # exists". No-op on SQLite (inline CHECK, no separate type object).
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("DROP TYPE IF EXISTS conversationstate")
